[project]
name = "sandbox-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shahiryar Ahmad", email = "shahiryarahmada7@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic[binary]>=1.19.1",
    "fastapi>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

